services:
  postgres:
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rentabike
      POSTGRES_USER: rentabike
      POSTGRES_PASSWORD: rentabike
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "rentabike", "-U", "rentabike"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

volumes:
  postgres: